app:
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000

spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

jwt:
  secret: 3f8a2b1c9d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000
