spring:
  datasource:
    url: jdbc:postgresql:///${DB_NAME}?cloudSqlInstance=${CLOUD_SQL_CONN}&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
  
  liquibase:
    contexts: '!dev,!test'

logging:
  level:
    aranya.crm: INFO